
export const activityType = {

  //Cada tipo de evento se vincula con una entidad definida en activityEntityType
  //PROJECT
  PROJECT_CREATED: "PROJECT_CREATED", //?ok
  PROJECT_UPDATED: "PROJECT_UPDATED",//?ok
  PROJECT_START_DATE_CHANGED: "PROJECT_START_DATE_CHANGED",//?ok
  PROJECT_DUE_DATE_CHANGED: "PROJECT_DUE_DATE_CHANGED",//?ok
  PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED",//?ok
  
  //PROJECT_TEAM
  PROJECT_TEAM_CREATED: "PROJECT_TEAM_CREATED",//?ok
  PROJECT_TEAM_UPDATED: "PROJECT_TEAM_UPDATED",//?ok
  PROJECT_TEAM_DELETED: "PROJECT_TEAM_DELETED",//?ok
  
  //PROJECT_TEAM_MEMBER
  PROJECT_TEAM_MEMBER_ADDED: "PROJECT_TEAM_MEMBER_ADDED",//?ok
  PROJECT_TEAM_MEMBER_REMOVED: "PROJECT_TEAM_MEMBER_REMOVED",
  PROJECT_TEAM_MEMBER_ROLE_CHANGED: "PROJECT_TEAM_MEMBER_ROLE_CHANGED",//?ok

  //PROJECT_COLLABORATOR
  PROJECT_COLLABORATOR_ADDED: "PROJECT_COLLABORATOR_ADDED", //?ok
  PROJECT_COLLABORATOR_REMOVED: "PROJECT_COLLABORATOR_REMOVED",//!No tiene metadata
  PROJECT_COLLABORATOR_ROLE_CHANGED: "PROJECT_COLLABORATOR_ROLE_CHANGED",//?ok

  //PROJECT_INVITATION
  PROJECT_INVITATION_SEND: "PROJECT_INVITATION_SEND", //(Tiene metadata)//?ok
  PROJECT_INVITATION_ACCEPTED: "PROJECT_INVITATION_ACCEPTED", //!No tiene metadata
  PROJECT_INVITATION_REJECTED: "PROJECT_INVITATION_REJECTED", //!No tiene metadata
  PROJECT_INVITATION_CANCELLED: "PROJECT_INVITATION_CANCELLED", //!No tiene metadata

  //TASK
  TASK_CREATED: "TASK_CREATED",//?ok
  TASK_UPDATED: "TASK_UPDATED",//?ok
  TASK_DELETED: "TASK_DELETED",//?ok
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",//?ok
  TASK_PRIORITY_CHANGED: "TASK_PRIORITY_CHANGED",//?ok
  TASK_ASSIGNED: "TASK_ASSIGNED", //!x
  TASK_UNASSIGNED: "TASK_UNASSIGNED", //!x
  TASK_START_DATE_CHANGED: "TASK_START_DATE_CHANGED",//?ok
  TASK_DUE_DATE_CHANGED: "TASK_DUE_DATE_CHANGED",//?ok
  TASK_COMPLETED: "TASK_COMPLETED",//?ok
  TASK_REOPENED: "TASK_REOPENED",//?ok
  
  //COMMENT
  COMMENT_CREATED: "COMMENT_CREATED",
  COMMENT_UPDATED: "COMMENT_UPDATED",//!No tiene metadata
  COMMENT_DELETED: "COMMENT_DELETED",
  
} as const


export const activityEntityType = {
  PROJECT: "PROJECT",
  PROJECT_TEAM: "PROJECT_TEAM",
  PROJECT_TEAM_MEMBER: "PROJECT_TEAM_MEMBER",
  PROJECT_COLLABORATOR: "PROJECT_COLLABORATOR",
  PROJECT_INVITATION: "PROJECT_INVITATION",
  TASK: "TASK",
  COMMENT: "COMMENT",
} as const